name: Mac

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  xcode_macos_13:
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ['15.0']
        build_type: [Release]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose

  macos_lateset:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler:
          - { cpp: g++-12, c: gcc-12}
          - { cpp: clang++, c: clang}
        build_type: [Release]
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}

    steps:
      - uses: actions/checkout@v3

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose