name: Update AoC Badges
on:
  schedule:                                      # run workflow based on schedule
    - cron: '6 5 1-25 12 *'                      # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)
    
  workflow_dispatch:                             # allow to manually start the workflow 
  
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 44566
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2024
          daysCompletedRegex: '(?<=\[2024\]\(https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red\))'  # Regular expression that finds the content of the days completed badge in your file.
          starsRegex: '(?<=\[2024\]\(https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow\))'
          
      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md